### PR TITLE
fix: try avoid nodejs 13.0.0 bug

### PR DESCRIPTION
**Pull request by bluelovers**
https://github.com/nodejs/modules/issues/446

### CODE REVIEW

**Comment by ai** [comment]
Did you tested this fix?

I can't find this solution in your link

**Comment by bluelovers** [comment]
sry my pc is not on my hand now, i can't test it
but this comment say it is requireable 

Screenshot_20200413-021514_GitHub

**Comment by ai** [comment]
This comment is saying about adding to a root level of `exports`, not to add it inside

**Comment by ai** [comment]
Sorry, we do not support old Node.js versions. You need to update Node.js.

**Pull request closed without merging**
